export default {
    WINDOW_RESIZE: 'WINDOW_RESIZE',
    OPEN_CART: 'OPEN_CART',
    CLOSE_CART: 'CLOSE_CART',
    OPEN_WISHLIST: 'OPEN_WISHLIST',
    CLOSE_WISHLIST: 'CLOSE_WISHLIST',

    ORIENTATION: {
        LANDSCAPE: 'LANDSCAPE',
        PORTRAIT: 'PORTRAIT'
    },

    FORWARD: 'FORWARD',
    BACKWARD: 'BACKWARD',

    OVERFLOW_VISIBLE: 'OVERFLOW_VISIBLE',
    OVERFLOW_HIDDEN: 'OVERFLOW_HIDDEN',

    TRIGGER_MOBILE_MENU: 'TRIGGER_MOBILE_MENU',
    OPEN_MOBILE_MENU: 'OPEN_MOBILE_MENU',
    CLOSE_MOBILE_MENU: 'CLOSE_MOBILE_MENU',

    LEFT: 'LEFT',
    RIGHT: 'RIGHT',
    TOP: 'TOP',
    BOTTOM: 'BOTTOM',

    OVERALL_PADDING: 40,
    HEADER_H: 63,

    MEDIA_GLOBAL_W: 1920,
    MEDIA_GLOBAL_H: 1080,

    MIN_MIDDLE_W: 960,
    MQ_XSMALL: 320,
    MQ_SMALL: 480,
    MQ_MEDIUM: 768,
    MQ_LARGE: 1024,
    MQ_XLARGE: 1280,
    MQ_XXLARGE: 1680
}
